--
-- Standard procedures to use CSV as a commom SQL table, to link or populate your database.
--   (this script is a cache, "kx_" prefixed file, generated by software from datapackage.json)
--
-- See step01_3-foreign_tables.sh
--

CREATE EXTENSION file_fdw;
CREATE SERVER csv_files FOREIGN DATA WRAPPER file_fdw;

--
-- Each standard CSV file and its fields definition
-- Check data model and migration scripts for more details about final use in the system.
--

/**
 * List of all articles (~4560000) in the PMC repo.
 * @see ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/PMC-ids.csv.gz
 */
CREATE FOREIGN TABLE tmpcsv_pmc_ids (
	Journal_Title text,
	ISSN text,
	eISSN text,
	Year int,
	Volume text,
	Issue text,
	Page text,
	DOI text,
	PMCID text,
	PMID bigint,
	Manuscript_Id text,
	Release_Date text
)   SERVER csv_files OPTIONS (
     filename '/tmp/obsjats/PMC-ids.csv',
       format 'csv',
       header 'true'
);

/**
 * License families.
 * @see https://github.com/ppKrauss/licenses/blob/master/data/families.csv
 */
CREATE FOREIGN TABLE tmpcsv_families (
    family text, scope text, sort int
) SERVER csv_files OPTIONS (
    filename '/tmp/obsjats/families.csv',  format 'csv',  header 'true'
);

/**
 * Licenses.
 * @see https://github.com/ppKrauss/licenses/blob/master/data/licenses.csv
 */
CREATE FOREIGN TABLE tmpcsv_licenses (
	id_label text,
	id_version text,
	name text,
	family text,
	is_ref integer,
	status text,
	year integer,
	is_by integer,
	is_sa integer,
	is_salink integer,
	is_nd integer,
	is_noreuse integer,
	is_generic integer,
	domain_content integer,
	domain_data integer,
	domain_software integer,
	od_conformance text,
	osd_conformance text,
	maintainer text,
	title text,
	url text,
	NOTES text
) SERVER csv_files OPTIONS (
    filename '/tmp/obsjats/licenses.csv',  format 'csv',  header 'true'
);

/**
 * Implied licenses.
 * @see https://github.com/ppKrauss/licenses/blob/master/data/implieds.csv
 */
CREATE FOREIGN TABLE tmpcsv_implieds (
	id_label text,
	id_version text,
	name text,
	family text,
	status text,
	year integer,
	report_year integer,
	is_by integer,
	is_sa integer,
	is_noreuse integer,
	is_generic integer,
	domain_content integer,
	domain_data integer,
	domain_software integer,
	od_conformance text,
	osd_conformance text,
	maintainer text,
	title text,
	url_report text,
	url_ref text
) SERVER csv_files OPTIONS (
    filename '/tmp/obsjats/implieds.csv',  format 'csv',  header 'true'
);

/**
 * Default licenses by science authorities.
 * @see https://github.com/ppKrauss/openCoherence/blob/master/data/samples/sciDocs/dftLicences-sciAuthorities.csv
 */
CREATE FOREIGN TABLE tmpcsv_dftlic_sciAuthorities (
    jou_id integer, jou_dftLicense text, jou_name int
) SERVER csv_files OPTIONS (
    filename '/tmp/obsjats/dftLicences-sciAuthorities.csv',  format 'csv',  header 'true'
);

/**
 * Science repositories.
 * @see https://github.com/ppKrauss/openCoherence/blob/master/data/sciRepos.csv
 */
CREATE FOREIGN TABLE tmpcsv_sciRepos (
    label text, name text, "repo-wikidataID" text, url text, "repo-wikidataID-rel" text, "url-dft-lincense" text
) SERVER csv_files OPTIONS (
    filename '/tmp/obsjats/dftLicences-sciAuthorities.csv',  format 'csv',  header 'true'
);

/**
 * XPath transducers.
 * @see https://github.com/ppKrauss/openCoherence/blob/master/data/xpathTransducers.csv
 */
CREATE FOREIGN TABLE tmpcsv__xpathTransducers (
    jkey_group integer, jkey text, transducer integer, xpath_str text, dtds text, xpath_ns text
) SERVER csv_files OPTIONS (
    filename '/tmp/obsjats/dftLicences-sciAuthorities.csv',  format 'csv',  header 'true'
);
